{{- if .Files.Get "tls.crt" }}
apiVersion: v1
kind: Secret
metadata:
  name: openshift-apiserver-serving-cert
  namespace: {{ .Values.namespace }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Files.Get "tls.crt" | b64enc }}
  tls.key: {{ .Files.Get "tls.key" | b64enc }}
{{- end }}
