apiVersion: v1
kind: Namespace
metadata:
  name: test
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: test-notebook
  namespace: test
spec:
  lookupPolicy:
    local: false
  tags:
  - name: latest
    from:
      kind: DockerImage
      name: quay.io/modh/odh-minimal-notebook-container:v3-2025b-20250826
